// @ts-check

/**
 * Sidebar tự sinh từ cấu trúc thư mục docs/.
 * Thứ tự đọc lấy theo tiền tố số của file (01-, 02-, ...) và
 * `position` trong các file _category_.json.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
